name: ClusterFuzzLite fuzzing
on:
  workflow_dispatch:
  push:
    branches:
      - main  # Use your actual default branch here.
  schedule:
    - cron: '*/6 * * * *'  # Every 6 minutes
permissions: read-all
jobs:
  BatchFuzzing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, memory, undefined] # Override this with the sanitizers you want.
    steps:
    - name: Build Fuzzers (${{ matrix.sanitizer }})
      id: build
      uses: google/clusterfuzzlite/actions/build_fuzzers@v1
      with:
        language: c # Change this to the language you are fuzzing.
        sanitizer: ${{ matrix.sanitizer }}
    - name: Run Fuzzers (${{ matrix.sanitizer }})
      id: run
      uses: google/clusterfuzzlite/actions/run_fuzzers@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        fuzz-seconds: 120 # 2 minutes
        mode: 'batch'
        sanitizer: ${{ matrix.sanitizer }}
        output-sarif: true
        # Optional but recommended: For storing certain artifacts from fuzzing.
        # storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/jmartins-ledger/test.git
        # storage-repo-branch: main   # Optional. Defaults to "main"
        # storage-repo-branch-coverage: gh-pages  # Optional. Defaults to "gh-pages".
  Pruning:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      id: build
      uses: google/clusterfuzzlite/actions/build_fuzzers@v1
      with:
        language: c # Change this to the language you are fuzzing
    - name: Run Fuzzers
      id: run
      uses: google/clusterfuzzlite/actions/run_fuzzers@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        fuzz-seconds: 120 # 2 minutes
        mode: 'prune'
        output-sarif: true
        # Optional but recommended.
        # storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/jmartins-ledger/test.git
        # storage-repo-branch: fuzz-corpus   # Optional. Defaults to "main"
        # storage-repo-branch-coverage: fuzz-coverage  # Optional. Defaults to "gh-pages".
  Coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      id: build
      uses: google/clusterfuzzlite/actions/build_fuzzers@v1
      with:
        language: c # Change this to the language you are fuzzing.
        sanitizer: coverage
    - name: Run Fuzzers
      id: run
      uses: google/clusterfuzzlite/actions/run_fuzzers@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        fuzz-seconds: 120 # 2 minutes
        mode: 'coverage'
        sanitizer: 'coverage'
        # Optional but recommended.
        # storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/jmartins-ledger/test.git
        # storage-repo-branch: fuzz-corpus   # Optional. Defaults to "main"
        # storage-repo-branch-coverage: fuzz-coverage  # Optional. Defaults to "gh-pages".

